### ISSUE TITLE
what are the meaning of 'newlag_v' and 'newlag_h' in DepthFirstStage.py?

### ISSUE THREAD

**Issue by fhys** [ZigZag-Project/DeFiNES#2]
I don't understand the lines 210-216 of code in DepthFirstStage.py. Why should we use this formula to calculate newlag_h and newlag_v? 
>                 newlag_h = SX * lag_h \
>                            - (input_loops[df_input_loop_X] - n.loop_dim_size[df_output_loop_X] * SX + SX -1)//2 \
>                            + input_overlap_X
> 
>                 newlag_v = SY * lag_v \
>                            - (input_loops[df_input_loop_Y] - n.loop_dim_size[df_output_loop_Y] * SY + SY -1)//2 \
>                            + input_overlap_Y
For 'input_loops[df_input_loop_X] - n.loop_dim_size[df_output_loop_X] * SX + SX -1', I consider it as FX-1, but why does FX-1 need to be divided by 2?

**Comment by YourDecesion** [comment]
I think newlag_h/v are used to caculate offset of input tiles for nodes whose out degree > 1, then get effective rows/columns cache number, as mentioned at Fig.8 of the paper https://arxiv.org/abs/2212.05344.

**Comment by fhys** [comment]
> I think newlag_h/v are used to caculate offset of input tiles for nodes whose out degree > 1, then get effective rows/columns cache number, as mentioned at Fig.8 of the paper https://arxiv.org/abs/2212.05344.
